namespace jevois { namespace font {
// created by font2c; source image: etc/fonts/7x13.png
// Image Width = 665, Height = 13
// Letter size = 7 x 13
#define WW 0x00
#define o  0xff
extern const unsigned char font7x13[95][91];
const unsigned char font7x13[95][91] = {
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,
    o ,WW,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    WW,o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    WW,o ,o ,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,
    WW,o ,o ,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,WW,o ,
    WW,o ,WW,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,WW,o ,
    WW,o ,o ,WW,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    WW,o ,WW,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,
    WW,o ,WW,o ,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,
    WW,o ,WW,WW,o ,WW,o ,
    WW,o ,WW,WW,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,WW,o ,o ,WW,o ,
    WW,o ,o ,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,WW,o ,o ,WW,o ,
    WW,o ,o ,WW,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,o ,
    WW,o ,WW,o ,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,WW,WW,o ,WW,o ,
    WW,o ,WW,WW,o ,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,o ,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,o ,WW,o ,
    WW,o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,o ,WW,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o
  }
};
#undef WW
#undef o

  } // namespace font
} // namespace jevois

