namespace jevois { namespace font {
// created by font2c; source image: etc/fonts/6x10.png
// Image Width = 570, Height = 10
// Letter size = 6 x 10
#define WW 0x00
#define o  0xff
extern const unsigned char font6x10[95][60];
const unsigned char font6x10[95][60] = {
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,WW,o ,WW,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,o ,WW,o ,o ,o ,
    WW,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,
    WW,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,WW,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    WW,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,o ,o ,
    WW,o ,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,
    WW,o ,WW,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,o ,WW,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,o ,o ,
    WW,o ,WW,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,WW,o ,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,WW,WW,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    o ,WW,o ,o ,WW,o ,
    o ,o ,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,o ,o ,
    WW,WW,WW,o ,o ,o ,
    WW,o ,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,o ,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,WW,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,
    o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,WW,o ,o ,
    WW,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,WW,o ,
    WW,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,WW,o ,
    WW,o ,WW,o ,WW,o ,
    WW,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o
  }
};
#undef WW
#undef o

  } // namespace font
} // namespace jevois

