namespace jevois { namespace font {
// created by font2c; source image: etc/fonts/9x15bold.png
// Image Width = 855, Height = 15
// Letter size = 9 x 15
#define WW 0x00
#define o  0xff
extern const unsigned char font9x15bold[95][135];
const unsigned char font9x15bold[95][135] = {
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,o ,
    WW,WW,o ,WW,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,o ,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o
  }
};
#undef WW
#undef o

  } // namespace font
} // namespace jevois

