namespace jevois { namespace font {
// created by font2c; source image: etc/fonts/8x13bold.png
// Image Width = 760, Height = 13
// Letter size = 8 x 13
#define WW 0x00
#define o  0xff
extern const unsigned char font8x13bold[95][104];
const unsigned char font8x13bold[95][104] = {
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,o ,WW,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,o ,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,WW,WW,WW,WW,o ,
    WW,WW,o ,WW,o ,o ,WW,o ,
    WW,WW,o ,WW,o ,o ,WW,o ,
    WW,WW,o ,WW,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,WW,WW,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,WW,WW,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,o ,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,o ,WW,o ,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,
    WW,WW,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,o ,
    WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o
  }
};
#undef WW
#undef o

  } // namespace font
} // namespace jevois

