namespace jevois { namespace font {
// created by font2c; source image: etc/fonts/12x22.png
// Image Width = 1140, Height = 22
// Letter size = 12 x 22
#define WW 0x00
#define o  0xff
extern const unsigned char font12x22[95][264];
const unsigned char font12x22[95][264] = {
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,
    WW,WW,WW,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    WW,WW,o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,WW,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,WW,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,WW,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,WW,WW,WW,
    o ,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,WW,WW,WW,WW,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,WW,o ,o ,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,o ,o ,o ,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,WW,o ,WW,WW,WW,WW,WW,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,WW,WW,WW,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,WW,WW,WW,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,WW,WW,WW,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,WW,WW,WW,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,WW,WW,WW,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,WW,WW,WW,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,WW,WW,WW,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,
    WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,WW,WW,
    WW,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,WW,WW,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,WW,WW,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,WW,WW,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,WW,WW,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,WW,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,o ,o ,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,WW,WW,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,WW,WW,
    WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,WW,WW,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,o ,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,
    o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,WW,WW,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  }
};
#undef WW
#undef o

  } // namespace font
} // namespace jevois

