#!/bin/bash
# USAGE: glsl-to-cpp.sh <outfile> <indir>
# Scans indir for *.glsl and, for each, create a char array named as the file's basename in namespace jevois::shader

echo "// Auto-generated by glsl-to-cpp.sh - DO NOT EDIT" > "$1"
echo >> "$1"
echo "namespace jevois { namespace shader {" >> "$1"
for f in $2/*.glsl; do
    echo "   ... processing ${f}"
    b="$(basename -- ${f} .glsl)"
    echo "// ###############################################################################################" >> "$1"
    echo "extern char const * ${b};" >> "$1"
    echo -n "char const * ${b} = R\"V0G0N(" >> "$1"
    cat "${f}" >> "$1"
    echo ")V0G0N\";" >> "$1"
    echo >> "$1"
done
echo "} } // namespace jevois::shader" >> "$1"
