#!/bin/bash
# USAGE: jevois-cmd [-d /dev/ttyACMX] command
#
# Send a command to a connected JeVois camera using the serial-over-USB port

ttydev="/dev/ttyACM0"
if [ "X$1" = "X-d" ]; then ttydev=$2; shift 2; fi 

if [ ! -c "$ttydev" ]; then echo "Cannot access $ttydev -- is JeVois plugged in? -- ABORT"; exit 1; fi

# First read any accumulated junk in the serial buffers:
while true; do
    sudo bash -c "read -s -t 0.05 -s < \"${ttydev}\""
    if [ $? -ne 0 ]; then break; fi
done

# Send the command:
sudo bash -c "echo \"$*\" > ${ttydev}"

# Get the reply, which may have multiple lines:


# FIXME: this misses lines of multiline replies. Probably need something better than 'read'


#tiout=5
#while true; do
#    answer=`sudo bash -c "read -s -t ${tiout} < ${ttydev} && echo -n \\${REPLY} | tr -d '\\n' | tr -d '\\r'"`
#    if [ $? -ge 128 ]; then
#	if [ $tiout -ne 5 ]; then exit 0; fi    # got some lines previously but no more: done
#	echo "Timeout communicating with JeVois -- ABORT"
#	exit 100
#    fi
#    if [ $? -ne 0 ]; then echo "Error communicating with JeVois -- ABORT"; exit 100; fi
#    echo ${answer}
#    tiout=1 # after we got the first line, use a shorter timeout for any subsequent lines
#done
