#!/usr/bin/perl
# USAGE: jevois-jvpkg <vendor> <module> [... <module>]
# Pack <vendor>-<module>.jvpkg package(s) from all the files in /var/lib/jevois-microsd/modules/<vendor>/<module>/

use File::Basename;

my $root = "var/lib/jevois-microsd/modules";
my $vendor = shift;

foreach my $module (@ARGV)
{
    my $src = "/${root}/${vendor}/${module}";
    my $pkg = "${vendor}-${module}.jvpkg";

    die "Cannot find directory $src -- ABORT" unless (-d "$src" );

    my @excludes=qw/video* jvpkg-exclude.cfg/;

    my @elist = `find $dir -name jvpkg-exclude.cfg`;
    foreach my $e (@elist) {
        chomp $e; my $dir = dirname($e);
        open F, $e || die "oops";
        while (my $line = <F>) { chomp $line; push(@excludes, "$dir/$line"); }
        close F;
    }

    my $tmpf = `mktemp`; chomp $tmpf;
    open F, ">$tmpf" || die "ooops";
    foreach my $e (@excludes) { print F "$e\n"; }
    close F;

    system("tar jcf ${pkg} --exclude-from $tmpf -C / ${root}/${vendor}/${module} --transform 's,^${root},jevois/modules,'");

    unlink($tmpf);

    print "Created ${pkg} from /${root}/${vendor}/${module}\n";
}
